FROM python:3.10-slim
MAINTAINER Tim Schopinski

ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY ./backend/dependencies /dependencies

RUN pip3 install -r dependencies/requirements.dev.txt

COPY ./backend /app/backend
RUN adduser django
RUN chown -R django /app

COPY ./compose/django/dev.sh /dev.sh


RUN chmod +x /dev.sh

WORKDIR /app

CMD ["dev.sh"]